### ISSUE TITLE
Potential bug for User Import

### ISSUE THREAD

**Issue by seed-doordash** [pulumi/pulumi-kafka#208]
### What happened?

We are trying to migrate from TF to Pulumi. 
When importing a Kafka Scram User, we cannot get this to work.

Our program code roughly looks like this (some parts ommitted)
```
	// handle import
	opts := make([]pulumi.ResourceOption, 0)
	if config.GetBool(ctx, "is_import") {
	        resourceId := config.Get(ctx, "resource_import_id")
		opts = append(opts, pulumi.Import(pulumi.ID(resourceId)))
	}
	options := append(opts, pulumi.Provider(kafkaProvider))
	if password == (pulumi.StringOutput{}) {
		return nil, errors.New("password not set")
	}

	args.UserScramCredentialArgs.Password = password

	user, err := kafka.NewUserScramCredential(
		ctx,
		fmt.Sprintf("%s", args.Username),
		args.UserScramCredentialArgs,
		options...,
	)
	if err != nil {
		return nil, err
	}
	ctx.Export("id", user.ID())
	ctx.Export("updatedAt", pulumi.StringPtr(fmt.Sprintf("%d", time.Now().Unix())))
	ctx.Export("password", password)

	return user, nil
```

**Our config looks like**
```
encryptionsalt: xxxxxx
config:
  username: "self_server_import_test_user_1"
  project: "storage-infra"
  owning_team: "TF-SG - PE Storage"
  max_produce_bytes: "-1"
  max_consume_bytes: "-1"
  cluster: "dd-kafka-local"
  target: "local"
  type: "kafka-user"
  name: "self_server_import_test_user_1"
  is_import: "true"
  vault_mode: "EXISTS"
  resource_import_id: "self_server_import_test_user_1|SCRAM-SHA-256"
```

**The pulumi preview shows**
```❯ pulumi preview
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your passphrase to unlock config/secrets
Previewing update (user-test-import):
     Type                                Name                                           Plan       Info
 +   pulumi:pulumi:Stack                 kafka-user-user-test-import                    create     1 error
 +   ├─ pulumi:providers:vault           vaultProvider                                  create
 +   ├─ pulumi:providers:kafka           kafka                                          create
 =   ├─ kafka:index:UserScramCredential  self_server_import_test_user_1                 import     1 error
 =   └─ kafka:index:Acl                  self_server_import_test_user_1-prefixed-group  import
Diagnostics:
  kafka:index:UserScramCredential (self_server_import_test_user_1):
    error: Preview failed: resource 'self_server_import_test_user_1|SCRAM-SHA-256' does not exist

  pulumi:pulumi:Stack (kafka-user-user-test-import):
    error: preview failed
```

However, the resource def exits, i even checked the TF state, it looks like this
```   
 {
      "module": "module.self_server_import_test_user_1",
      "mode": "managed",
      "type": "kafka_user_scram_credential",
      "name": "kafka_user",
      "provider": "provider[\"registry.terraform.io/mongey/kafka\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "self_server_import_test_user_1|SCRAM-SHA-256",
            "password": "REDACTED",
            "scram_iterations": 4096,
            "scram_mechanism": "SCRAM-SHA-256",
            "username": "self_server_import_test_user_1"
          },
          "sensitive_attributes": [
            [
              {
                "type": "get_attr",
                "value": "password"
              }
            ]
          ],
          "private": "bnVsbA==",
          "dependencies": [
            "data.aws_secretsmanager_secret_version.password",
            "data.aws_secretsmanager_secret_version.username",
            "module.self_server_import_test_user_1.aws_secretsmanager_secret.kafka_user_password",
            "module.self_server_import_test_user_1.aws_secretsmanager_secret_version.kafka_user_password",
            "module.self_server_import_test_user_1.random_password.password"
          ]
        }
      ]
    },
```
So the ID is def `self_server_import_test_user_1|SCRAM-SHA-256`, what's going on here?

### Expected Behavior

should be able to import

### Steps to reproduce

1. pulumi login 
2. pulumi init
3. edit the config to be
```
config:
  username: "self_server_import_test_user_1"
  project: "storage-infra"
  owning_team: "TF-SG - PE Storage"
  max_produce_bytes: "-1"
  max_consume_bytes: "-1"
  cluster: "dd-kafka-local"
  target: "local"
  type: "kafka-user"
  name: "self_server_import_test_user_1"
  is_import: "true"
  vault_mode: "EXISTS"
  resource_import_id: "self_server_import_test_user_1|SCRAM-SHA-256"
  ```
4. run pulumi preview

### Output of `pulumi about`
```
❯ pulumi about
CLI
Version      3.82.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.17.0
go      unknown
kafka   3.5.0
random  4.13.0
vault   5.13.0
vault   4.6.0

Host
OS       darwin
Version  13.5
Arch     arm64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.21.1 darwin/arm64'

Backend
Name           YK39G2JQXG
URL            s3://doordash-pulumi-state-local
User           seedzeng
Organizations

Dependencies:
NAME                                    VERSION
github.com/go-playground/validator/v10  10.11.2
github.com/hashicorp/go-multierror      1.1.1
github.com/pulumi/pulumi-aws/sdk/v5     5.17.0
github.com/pulumi/pulumi-kafka/sdk/v3   3.5.0
github.com/pulumi/pulumi-random/sdk/v4  4.13.0
github.com/pulumi/pulumi-vault/sdk/v4   4.6.0
github.com/pulumi/pulumi-vault/sdk/v5   5.13.0
github.com/pulumi/pulumi/sdk/v3         3.76.0
github.com/rs/zerolog                   1.28.0
github.com/stretchr/testify             1.8.3
github.com/vmanikes/Functionality       0.1.0
k8s.io/utils                            0.0.0-20221128185143-99ec85e7a44
```

### Additional context
We are able to import all other resources like topic and acl.
It's just the scram user we are having trouble. 

The "id" for other resources in the TF state all matchs

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
